apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 3000   # Porta que o serviço expõe
      targetPort: 3000  # Porta dos pods
  type: NodePort  # Você pode usar  ClusterIP aqui se não precisar acessar de fora